In [3]:
import numpy as np

---
### Bracket indexing and selection of 1D array (vectors)
---

In [5]:
arra = np.arange(11)             # reating a sample array from 0 to 10, i.e it includes 11 elements
print(arra)                      # in this array element 0 is at index 0 and 10 at index 10
print(len(arra))                 # length is 11 as it contains 11 elements but index is from 0 to 10 as index count starts from 0 but length count from 1
# In this example 0 is at 0th index, 1 is at 1st index and so on

[ 0  1  2  3  4  5  6  7  8  9 10]
11


In [ ]:
# Elements at each index of an 1D array (quite similar to indexing in case of lists in python)

print(arra[0])                      # returns element at index 0
print(arra[10])                     # returns element at index 10
# print(arra[12])                   # returns 'index error' if the index exceed total number of elements in the array

print(arra[-1])                     # this is called negative indexing and returns -1 returns the last element of the array
print(arra[-3])                     # gives the third last element (i.e 8 in this case) due to negative indexing
print(arra[-11])                    # as our original array 'arra' had 11 elements it gives the first element of the array due to negative indexing
# print(arra[-15])                  # gives 'index error' as -15 index is greater than total elements in the 'array'(-11 is the last index)

# Normal indexing -> idx[0] to idx[len_array-1]
# Negative indexing -> idx[-len_array] to idx[-1]

0
10
10
8
0


---
### Array slicing (cool name)
---

In [ ]:
# Selection of multiple elements in an 1D array (quite similar to list slicing or string slicing)
# array_name[start_index(default = 0) : stop_idx(default = end_idx of the array) : step(or order)(default = 1(i.e every element))]

print(arra[0:5])                       # Output:  [0 1 2 3 4]   # grabs elements from 0th index uptil (end-1)th index. Here from 0th index to 4th index
print(arra[1:8])                       # grabs elements from 1st idx to 7th idx
print(arra[1:88])                      # when the stop_idx exceeds the total index, it grabs all the elements from the star_idx to the end of the array
print(arra[2:])                        # if we want to grab all the elements from specified start_idx up until end of array, we can pass black in place of end_idx
print(arra[9:5])                       # returns blank array [] if start_idx > end_idx
print(arra[:5])                        # grabs every element from 0th idx to (end-1)th idx
print(arra[:88])                       # grabs every element in the array as start_idx(default) and end_idx > total_idx in arra
print(arra[:])                         # if we do not pass any value(start or stop) it grabs every element in array due to default parameter
print(arra[-8:-1])                     # same logic for nrgative slicing but there start_idx = -(len_array) and end_idx = -1
print(arra[-9:8])                      # we can mix negative and positive idx but the rules remains same, negative idx corresponds to the +ve index thats it is of


[0 1 2 3 4]
[1 2 3 4 5 6 7]
[ 1  2  3  4  5  6  7  8  9 10]
[ 2  3  4  5  6  7  8  9 10]
[]
[0 1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[3 4 5 6 7 8 9]
[2 3 4 5 6 7]


In [41]:
# Changing step parameter in array slicing
# (+) -> means normal order of the array(left to right) ; (-)ve -> means reverse order(right to left)

print(arra[0:10:1])                # prints every index from 0th index to 9th index as step-count is 1
print(arra[0:10:2])                # Output: [0 2 4 6 8] ; prints every alternate element as step count is 2
print(arra[0:10:3])                # Output: [0 3 6 9] ; prints every other third element

# reversing order: we have to change start idx and end idx, when step becomes -1, rules also becomes reverse

print(arra[10:5:-1])          # normall start_idx . end_idx but as step = -1, prints all elemnts from 10th idx to 6th idx i.e (end+1)th idx
print(arra[::-1])             # reverses the whole array , similar to print(arra[11:-1:-1])
print(arra[11::-1])           # Here we can't write the end_idx to reverse the whole array, but 11 or 10 at start_idx is completely fine
print(arra[10:5:-2])          # Output: [10  8  6]    # prints every alt element from 10th idx to 6th idx


[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 3 6 9]
[10  9  8  7  6]
[10  9  8  7  6  5  4  3  2  1  0]
[10  9  8  7  6  5  4  3  2  1  0]
[10  8  6]


---
### Broadcasting
---

In [ ]:
print(arra)                          # just for reference

[ 0  1  2  3  4  5  6  7  8  9 10]


In [ ]:
# As arrays are mutable like lists, we can actuall change an element at a certain index or multiple index elements:

arra[5] = 99                 # we have changed the element at index 5 of the array "arra" to 99

print(arra)                  # the original array has been changed
print(arra[5])


[ 0  1  2  3  4 99  6  7  8  9 10]
99


In [ ]:
# Changing multiple elements of the array:

a = np.arange(0,12)
print(a)

a[2:10] = 39                 # all elements from idx 2 to idx 9 will become 39
print(a)                     # all the elements of the specified index has changed to 39 in the original array
print(a[2:10])
# this method acts for all of negative indexing etc, Just we have to follow the rules

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1 39 39 39 39 39 39 39 39 10 11]
[39 39 39 39 39 39 39 39]


In [ ]:
# In numpy there is no copy by default the actual array changes unless we copy using .copy() method

arr = np.arange(0,16)           # Creating a reference array
print(arr)

array_broadcast = arr

array_broadcast[2:7] = 69      # all the elements from idx 2 to idx 6 of the array "array_broadcast" will become 69

print(array_broadcast)         # this will print the changed array with 69's
print(arr)                     # it also changes becaise in numpy due to memory management both array_broadcast and arr points to the same object. So changing one changes bot. Numpy does not create a copy of the array until we specify 


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[ 0  1 69 69 69 69 69  7  8  9 10 11 12 13 14 15]
[ 0  1 69 69 69 69 69  7  8  9 10 11 12 13 14 15]


In [ ]:
# Creating copy so that original array remains same

arr1 = np.arange(0,15)                 # Creating a reference array
print(arr1)

array_broadcast_1 = arr1.copy()        # copying arr1 to array_broadcast_1

array_broadcast_1[1:9] = 67            # changing the elements from idx 1 to idx 8 to 67 in the array "array_broadcast_1"
 
print(array_broadcast_1)               # the changed array
print(arr1)                            # remains exactly the same as before as the changes have been done to its copy not the original one


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0 67 67 67 67 67 67 67 67  9 10 11 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


---
## Indexing a 2d array(matrices)
---

In [ ]:
# Creating reference matrix:
array_2D = np.array([[5,10,15],[25,30,35],[45,50,55]])
print(array_2D)                      

[[ 5 10 15]
 [25 30 35]
 [45 50 55]]


In [67]:
# Indexing in 2D array is similar to grabbing elements from a nested loop:
# There are two was of doing : (i) array_2D[idx][idx] & (ii) array_2D[idx,idx] --> similar to what we do in case of nested lists

# Basically its like : array_2D[row,columnn] or array_2D[row][column] both indexes of row and columns starts from 0

# Grabbing 10
print(array_2D[0][1])     # Or
print(array_2D[0,1])

# Logic : In a matrix( 2D array) each row has an index starting from 0(top) to number of rows(bottom). Again on each row every element has an index starting
#         from 0(left) to no of elements in that row(right)

# Grabbing 5:
print(array_2D[0])                 # returns the first row(idx 0); as 5 is an element of 1st row
print(array_2D[0][0])              # returns first element(idx 0) of 1st row(idx 0) i.e 5

# Grabbing 30:
print(array_2D[1,1])               

# Grabbing 50:
print(array_2D[2,1])

# Grabbing the second row:
print(array_2D[1])


10
10
[ 5 10 15]
5
30
50
[25 30 35]


----
### Matrix slicing(Grabbing multiple elements)
----

In [68]:
print(array_2D)

[[ 5 10 15]
 [25 30 35]
 [45 50 55]]


In [ ]:
# here we do no operate row and column together, We first do row slicing and then column slicing and seperate then by comma.
# [Remember: all rows and columns starts from 0]
# Format : array_2D[row_idx : row_idx , column_idx:column_idx]  &  the ending row or column index will not get printed , the element before that will get printed at last

# Grabbing top (left) four elements i.e (5,10 and 25,30)
print(array_2D[0:2])        # prints first two rows
print(array_2D[0:2,0:2])    # prints 2x2 matrix from top left corner
# OR
print(array_2D[:2,:2])      # slicing rules also gets applied here, insed of writing idx 0 we can basically skip it

# Grabbing bottom left corner in order 2x2 (i.e 30,35 and 50,55)
print(array_2D[1:3,1:3])    # Don't forget ending index never gets prited
#OR
print(array_2D[1:,1:])

# Grabbing column 3 ,i.e column with idx 2
print(array_2D[:,2:])       # we have to take every row and only the column with index 2

# Grabbing 2nd and third row
print(array_2D[1:])        


[[ 5 10 15]
 [25 30 35]]
[[ 5 10]
 [25 30]]
[[ 5 10]
 [25 30]]
[[30 35]
 [50 55]]
[[30 35]
 [50 55]]
[[15]
 [35]
 [55]]
[[25 30 35]
 [45 50 55]]


---
## Conditional Selection
---

In [ ]:
# Creating sample array(1D)
arr_1 = np.arange(0,13)
print(arr_1)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
bool_arr = arr_1 > 3   # returns a boolean 1D array for each element with true and false. true if the condition is met and false if not. Here cond: >3
print(bool_arr)
# Or directly we can do:
print(arr_1 >3)
# hence its called conditional selection

[False False False False  True  True  True  True  True  True  True  True
  True]
[False False False False  True  True  True  True  True  True  True  True
  True]


In [ ]:
# Conditional selection/indexing/slicing : returns single or multiple elements of the array which follows a certain condition

# Conditionally selecting elements from the original arr_1 array:
print(arr_1[bool_arr])         # returns the elements which came as true in bool_arr i.e elements > 3. Hence its called conditional selection as its based on a condition

print(arr_1[arr_1>5])          # returns the elements in the array "arr_1" which are greater than 5
print(arr_1[arr_1 > 10])       # Output : [11 12] -> elements in arr_1 which are greater than 10

x = 7
print(arr_1[arr_1>x])          # returns the elements in the array "arr_1" which are greater than x i.e 7


# Edge cases:

print(arr_1[arr_1>19])         # returns empty array []
print(arr_1[arr_1<0])          # returns empty array []


[ 4  5  6  7  8  9 10 11 12]
[ 6  7  8  9 10 11 12]
[11 12]
[ 8  9 10 11 12]
[]
[]


---
### Some pieces of info 
---

In [ ]:
# Length of a matrix (2D array) is equal to the number of rows it has (starting from 1) -> not like indexing
print(len(np.zeros((8,44))))


8


---
### Homework : Fancy indexing in 2D matrix
---

In [ ]:
# Reference array of 2D with 50 elements
matrix = np.arange(50).reshape(5,10)
print(matrix)
print(len(matrix))     # will be 5 as number of rows is 5

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
5


In [97]:
# Grabbing 12,13,14:
e1 = matrix[1:2,2:5]
print(e1)

[[12 13 14]]


In [99]:
# Grabbing 34,35:
e2 = matrix[3:4,4:6]
print(e2)

[[34 35]]


In [100]:
# Grabbing 23,24:
e3 = matrix[2:3,3:5]
print(e3)

[[23 24]]
