In [2]:
# # Creating numpy array from a list:

import numpy as np

my_list = [4,6,9]

arr = np.array(my_list)       # np.array casts our list to an array

arr                           #-> returns array([4, 6, 9]) ,special feature in Jupyter that reads the last line of code and give interactive returns for developers clearly stating type of output

# print(arr)                  #-> returns [4 6 9]-> uses clean formatting for end user



array([4, 6, 9])

---
### Creating 1D and 2D array (i.e vectors and maxtrix)
---

In [16]:
# 1D array -> Vectors

my_vector = np.array([15,5,8,44,89,20])        # must include the outermost [] as it is a positional argument

print(my_vector)                      # without print we can't view it as its not on the last line
# print(my_vector)

# 1D array from list

my_list1 = [45,12,34,77,89,1,10]
my_vector1 = np.array(my_list1)

my_vector1                                 #- Now Jupyter will not show my_vector as it reads only the last line




[15  5  8 44 89 20]


array([45, 12, 34, 77, 89,  1, 10])

In [ ]:
# 2D array -> Matrix

my_matrix = np.array([[1,5,6],[81,77,56],[7,10,14]])              # each sublist represents each row and total number of sublists represents no of columns
# my_matrix = np.array([1,5,6],[81,77,56],[7,10,14])         --> must include the outside []

print(my_matrix)

# 2D array from list:
my_list =([[1,5,6],[81,77,56],[7,10,14]])           # we use nested lists for 2D matrix
my_matrix1 = np.array(my_list)
my_matrix1


[[ 1  5  6]
 [81 77 56]
 [ 7 10 14]]


array([[ 1,  5,  6],
       [81, 77, 56],
       [ 7, 10, 14]])

---
### Built in methods to generate array(both vectors and matrix) without typing every element


---
### (i) arange method
---

In [ ]:
# Creating 1D array with arange:
# np.arrange (start(default=0), upto stop, step(default=1))

arr = np.arange(12)               # creates a 1D array from 0 to 11
print(arr)

arr1 = np.arange(3,18)            # creates a 1D array from 0 to 17
print(arr1)

arr2 = np.arange(0,11,2)          # create a 1D array from 0 to 10 skipping every alt number
print(arr2)                       # output -> [ 0  2  4  6  8 10]


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
[ 0  2  4  6  8 10]


In [ ]:
# Creating 2D array with arange and reshape

arr = np.arange(12).reshape(3,4)      # reshape must include parameteres that product to the no of elements in array (i.e 3x4=12 -> here)
print(arr)

arr1 = np.arange(12).reshape(6,2)    # works perfectly as 6x2=12
print(arr1)

# arr2=np.arange(12).reshape(4,4)        # gives error as 4x4 != 12
# print(arr2)

# If you do not want to calculate the math for one of the dimensions, we can pass -1 into reshape. NumPy will automatically calculate the correct size for that dimension

arr3 = np.arange(0,200).reshape(5,-1)     # we have to pass atleast one parameter in reshape which will be sivisible by no of elements in arange  
arr3

---
### (ii) Generating arrays of only 0 and 1
---

In [ ]:
# Crating arrays with all elemnts 0

# Creating 1D void/zero array
print(np.zeros(3))             # creats a 1D array(vector) of cloumn length 3 with elements only 0

# Creating 2D void matrix
print(np.zeros((1,3)))         # gives same output but this time 2D marix of 1x3,(its not a vector now)

matrix_1 = np.zeros((5,9))     # by passing the tuple it creates a matrix of 5x9 (i.e rows 5 and columns 9)
print(matrix_1)                # gives a 5x9 null matrix




[0. 0. 0.]
[[0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
# Crating arrays with all elemnts 1

# Creating 1D vectors

print(np.ones(8))                    # Output -> [1. 1. 1. 1. 1. 1. 1. 1.]

# Creating 2D matrix

mat = np.ones((1,8))                 # Output same but this time its a matrix (two[])     
print(mat)

mat_1 = np.ones((5,7))                      # creates a matrix of order 5x7 with only 1
print(mat_1)


[1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


---
### (iii) Linspace method
---

In [ ]:
# Return evenly spaced numbers in a 1D array over a specific interval

# np.linspace(start,stop,num)

#np.linspace(start, stop(included), no of evenly spaced elements in that start-stop interval(default=50))--> we must pass start, stop as argument

arr1 = np.linspace(0,100,11)   #-> it will start from 0 and go to 100 by printing 11 evenly spaced numbers inclusing 0 and 100
print(arr1)                    #-> returns an 1D array

arr2 = np.linspace(0,98)      # here only start and stop arg. are passed, default specific value is 50
print(arr2)

arr3 = np.linspace(0,200,60)    #-> fractional no will get printed
print(arr3)                     # -> 1D array


[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64. 66. 68. 70.
 72. 74. 76. 78. 80. 82. 84. 86. 88. 90. 92. 94. 96. 98.]
[  0.           3.38983051   6.77966102  10.16949153  13.55932203
  16.94915254  20.33898305  23.72881356  27.11864407  30.50847458
  33.89830508  37.28813559  40.6779661   44.06779661  47.45762712
  50.84745763  54.23728814  57.62711864  61.01694915  64.40677966
  67.79661017  71.18644068  74.57627119  77.96610169  81.3559322
  84.74576271  88.13559322  91.52542373  94.91525424  98.30508475
 101.69491525 105.08474576 108.47457627 111.86440678 115.25423729
 118.6440678  122.03389831 125.42372881 128.81355932 132.20338983
 135.59322034 138.98305085 142.37288136 145.76271186 149.15254237
 152.54237288 155.93220339 159.3220339  162.71186441 166.10169492
 169.49152542 172.88135593 176.27118644 179.66101695 183.05084746
 186.44067797 

In [4]:
# Creating 2D matrix using linspace and reshape

mat1 = np.linspace(0,98,50).reshape(-1,5)       #-> any one of the reshape arg must be divisible by num
print(mat1)


#Creating 2D matrix using Multi-dimensional linspace  

# Starts for 3 different rows, stops for 3 different rows, generating 4 columns
matrix = np.linspace(start=[0, 10, 20], stop=[5, 50, 100], num=4, axis=1)         # num here creates no of elements in a single row which are evenly spaced
print(matrix)

# actually here are 4 linspace in matrix (0,5,4) ; (10,50,4) and (20,100,4)


[[ 0.  2.  4.  6.  8.]
 [10. 12. 14. 16. 18.]
 [20. 22. 24. 26. 28.]
 [30. 32. 34. 36. 38.]
 [40. 42. 44. 46. 48.]
 [50. 52. 54. 56. 58.]
 [60. 62. 64. 66. 68.]
 [70. 72. 74. 76. 78.]
 [80. 82. 84. 86. 88.]
 [90. 92. 94. 96. 98.]]
[[  0.           1.66666667   3.33333333   5.        ]
 [ 10.          23.33333333  36.66666667  50.        ]
 [ 20.          46.66666667  73.33333333 100.        ]]


---
### (iv) Identity matrix
---

In [ ]:
# Identity matrix is a sq matrix whose diagonal elements are 1 and all other elements are 0

identity_matrix = np.eye(4)              #-> np.eye takes only one argument as an Identity matrix is always square, hence only one arg is enough to tell the order of the matrix
                                         
print(identity_matrix)                   # Output : an identity matrix or order 4x4

# identity_matrix1 = np.eye(4.5)         # order is always an intiger
# print(identity_matrix1)                # error


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
### (v) Random number array
---

(a): rand: all no. between 0 to 1 have the equal probability of appearing


In [ ]:
# np.random.rand(order) : it populates an array (may be 1D or 2D) with random smaples in interval [0,1)-> 1 not included
# Order of this 1D or 2D array is decided by just writing the order without extra parenthesis --> 1D == np.random.rand(x) ; 2D == np.random.rand(y,x) or (x,1)
# This method will give a new array every time we run it with random samples in b/w 0 and 1

# Creating a 1D array of random samples:

vector1 = np.random.rand(5)                # creates a 1D array with 5 elements that is 5 random samples within interval [0,1)
print(vector1)                             # output -> [0.82283039 0.54720919 0.18223984 0.86635377 0.53787748]

vector2 = np.random.rand(10)               # creates a 1D array with 10 elements that is 10 random samples within interval [0,1)
print(vector2)

# without argument -> default 1
vector3 = np.random.rand()                 # default of order is 1, so it will create a random sample each time we run it if we haven't passed an argument
print(vector3)

vector4 = np.random.rand(0)               # creates an empty 1D array
print(vector4)                            # output : []
 

[0.60014799 0.77708713 0.01805568 0.97009743 0.67602998]
[0.54638663 0.26095454 0.41117131 0.79468192 0.57641109 0.69944294
 0.17554383 0.71602593 0.99558397 0.24711379]
0.40190066934463786
[]


In [ ]:
# Creating 2D array(matrix) of random sample: just pass no. normally, don't pass a tuple like in zeros or ones matrix

matrix_1 = np.random.rand(2,3)                 # creates a matrix with random sample(elements) b/w 0 to 1 in order 2x3
print(matrix_1)                                # output -> [[0.21426233 0.88872949 0.45622401]
#                                                          [0.96116692 0.99084657 0.77549669]]
      
matrix_2 = np.random.rand(1,3)                 # creates a matrix with random sample(elements) b/w 0 to 1 in order 1x3 --> its not a 1D array
print(matrix_2)

matrix_3 = np.random.rand(0,0)                 # creates an empty 1D array not matrix
print(matrix_3)                                # output-> []

matrix_4 = np.random.rand(1,1)                 # creates a singular 2D array(matrix)
print(matrix_4)

# similar to 1D array all of these changes values with every run


[[0.59337578 0.88486292 0.85032942]
 [0.41119382 0.28565559 0.25803229]]
[[0.24055178 0.05904877 0.49778632]]
[]
[[0.12522441]]


---
 (b):randn : follows standard normal distribution i.e will have mean=0 and standard deviation = 1, so no. closer to 0 have the highest chance of appearin in either direction



In [ ]:
# np.random.randn(order) : it populates an array (may be 1D or 2D) with random smaples from standard normal distribution in intarval (-∞,∞)
# Order-> same logic as np.random.randn
# it's also called a gausian distribution and plottion enough of these points gives a bell curve

# Generate a single random number
single_val = np.random.randn()                       # unlike rand it doesn't give a blank 1D array
print(single_val)

# Generate a 1D array of 5 numbers
array_1d = np.random.randn(5)                        # creates in interval (-∞,∞) but generally b/w -1.0 to 1.0
print(array_1d)

# Generate a 2D array (Matrix) of 3 rows and 4 columns
matrix_2d = np.random.randn(3, 4)                    # examples and order will be same as rand but noly element selection will be different   
print(matrix_2d)


0.15534401907938905
[ 0.35448223  1.05294236 -1.66995754  0.52535225 -0.36347834]
[[-1.54737025  0.47258733 -2.14582318  1.03452626]
 [ 0.95949434  0.78394098  0.84024436  0.60095853]
 [-0.2509555   0.47081012  1.30956212 -0.33925841]]


---
(c):randint: Returns random intigers in 1D array form, from low(inclusive) to high(exclusiv) based on number of intigers we want

In [ ]:
# np.random.randint(start(may be chosen),stop(will never be chosen), number of random int we want in start-stop interval(default=1)) -> we have to pass atleat one parameter which will be taken as upper boundary
# will return 1D array of "truely random" int(not evenly spaced, never floating values)

#np.random.randint(x,y,z) -> x < y and x!=y ; z(default 1) ; z must be positive intiger=> if np.random.randint(p) -> p = y . Violation = error

int1 = np.random.randint(5)               # generates one random int smaller than 5, here 5 is the upper boundary
print(int1)

int2 = np.random.randint(5,17)            #  generates one random int in interval [5,17), here stop must > start
print(int2)

int3 = np.random.randint(5,17,5)         #  generates five random int in interval [5,17), here stop must > start
print(int3)              

int4 = np.random.randint(8,22,100)       # z can be any number may be bigger than interval-> values will repeat to give required no. of intigers in that interval
print(int4)

int5 = np.random.randint(8,11,0)         # gives a blank 1D array 
print(int5)                              # output->[]


2
11
[ 9 14 12 11  6]
[ 8 18 14 12 13 19 10 16 16 11 16 14 17 15 20 12  9 19 20 21 10  8 15 21
 19 20 12 20 21 20 17 10 10 12 15  9 17 19 16  9 15 12 10 20 17 11 16 12
  9 18 21 18 16 17 19 15 21 17 20 15 14 12 12 18  9 12 21 19 13 18 20 10
 11 21 21 18 20 15 11 16 10 20 17 21 13 10 17 16 16 10 13 11 19  8 11 11
 14 21 16  8]
[]


---
## Array attributes and methods
---

### (i): Reshape function

In [ ]:
# For 1D arrays(vectors)
#.reshape(x,y)           -> product of x and y must be eqal to total no of elements in the array(1D); We must pass atleast 1 arg that is divisible by total no. of elements and for the next arg we can pass -1 
# x -> row no. and y -> column no.

arr_1d = np.arange(0,40)     #  1D array with elements from 0 to 45(excluded)
print(arr_1d)

r1 = arr_1d.reshape(10,4)        # creates a 2D array(matrix) with same elements of arr_1d but arranged in a specific order 
print(r1)                        # Note  : the product of the order must be equal to the total number of elements in the array otherwise error 

# r2 = arr_1d.reshape(9,58)      # a 9x58 order array can't be mede out of 40 elemnts
# print(r2)

r2 = np.array([1,4,6,76,23,24]).reshape(3,-1)                 # as it is 1D array with 6 elements it will reshape to 3x2 or 2x3 but bt writing -1 , it will automatically take the second argument
print(r2)

# we can add .reshape(x,y) at the end of any otherfunction

arr_1 = np.random.randint(12,21,20)          # will create a 1D array of 20 elements 
print(arr_1)                                 # always creates a 1D array
r3 = arr_1.reshape(5,-1)
print(r3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]
[[ 1  4]
 [ 6 76]
 [23 24]]
[13 13 17 13 16 13 17 12 19 14 20 12 20 15 14 13 16 19 14 16]
[[13 13 17 13]
 [16 13 17 12]
 [19 14 20 12]
 [20 15 14 13]
 [16 19 14 16]]


In [ ]:
# For 2D array(matrix) -> it will reshape existing 2D array into a new order if possible 

m1 = np.random.rand(8,3)            # creates a matrix of order 8(rows) x 3(columns) i.e with 24 elements
print(m1)
re1 = m1.reshape(6,4)               # reshapes the 8x3 matrix to 6(rows) x 4(columns)
print(re1)

# Can also be done directly
print(np.random.rand(9,4).reshape(-1,6)) # Converts 9x4 matrix into 6x6 matrix. We can't pass two arg as -1, atleast one arg has to be a multiple of total elements


[[0.01389109 0.46818395 0.42377871]
 [0.56564364 0.07736626 0.02029614]
 [0.06087804 0.2630088  0.38400161]
 [0.87504088 0.7287765  0.69394682]
 [0.59945647 0.84343116 0.63097605]
 [0.98734951 0.07568673 0.46789468]
 [0.30786312 0.33575815 0.68751276]
 [0.66527713 0.74587985 0.1882238 ]]
[[0.01389109 0.46818395 0.42377871 0.56564364]
 [0.07736626 0.02029614 0.06087804 0.2630088 ]
 [0.38400161 0.87504088 0.7287765  0.69394682]
 [0.59945647 0.84343116 0.63097605 0.98734951]
 [0.07568673 0.46789468 0.30786312 0.33575815]
 [0.68751276 0.66527713 0.74587985 0.1882238 ]]
[[0.11454396 0.19369592 0.28888679 0.03450125 0.16675809 0.67408178]
 [0.96437576 0.02332144 0.13609297 0.50159286 0.87699094 0.75913309]
 [0.84861616 0.12322351 0.46747103 0.12513994 0.9746718  0.5998723 ]
 [0.23526785 0.73438598 0.47115103 0.71368232 0.78609236 0.29402903]
 [0.86100754 0.51966528 0.16786118 0.27940908 0.15382859 0.10413964]
 [0.15764246 0.98806675 0.33382627 0.37608059 0.86954027 0.29495463]]


---
### (ii) Max, min, argmax, argmin functions
---

In [ ]:
# Max function and argmax : .max() returns the max element by value of a 1D or 2D array, if there are multiple max values it only returns the first occurance of the value
# argmax returns the index of the max value in the array : for multiple max values, returns the  index of occurance of the max value(index starts from 0)

# For 1D arrays:
v1 = np.arange(2,22)               # The max value will be 21
print(v1)
print(v1.max())                    # max() doesn't take any argument
print(v1.argmax())                 # returns the index of 21 in the array-> same as list index

v2 = np.random.rand(8)                # gives the max value of array 
print(v2)
print(v2.max())
print(v2.argmax())                    # returns the index of the max value

v3 = np.random.randint(10,19,20)            # in this specific run 18 is the highest no and 18 has occured thrice
print(v3)
print(v3.max())
print(v3.argmax())                          # returns the index of first occurance of max value 


[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
21
19
[0.95402006 0.01893851 0.62302217 0.62554339 0.88112328 0.05751581
 0.57875956 0.48835719]
0.9540200608735456
0
[12 14 18 15 14 10 11 13 17 16 15 18 17 18 13 12 12 10 18 11]
18
2


In [ ]:
# For 2D array: 
# argmax index for 2D array is counted from the top left element row-wise(horizontally) till the last bottom right element

matrix1 = np.random.rand(5,5)
print(matrix1)
print(matrix1.max())
print(matrix1.argmax())


[[0.49257271 0.57038365 0.97890623 0.26279324 0.75383105]
 [0.80365036 0.43196379 0.79966286 0.25451905 0.36930312]
 [0.41895991 0.04289726 0.43640658 0.50303932 0.00566892]
 [0.91844207 0.00116753 0.70693947 0.85477938 0.03467764]
 [0.86459642 0.2079005  0.17049358 0.58427058 0.57869631]]
0.978906233985454
2


In [24]:
# Min function: Gives the minimium value
# argmin-> the the index of first occurance of minimum value; logic same as argmax

# For 1D array
vec1 = np.random.randint(0,12,25)              # multiple min values
print(vec1)
print(vec1.min)                               # gives object location
print(vec1.min())
print(vec1.argmin())                          # returns index of occurance of first min value in case of multiplr


# For 2D array
ma1 = np.random.randn(5,5)
print(ma1)
print(ma1.min())                   # minimum value is negative in this case
print(ma1.argmin())                # for 2D array index same logic as argmax-> topleft to bottom right row-wise


[ 5  2 10  8  0  2 10  6 11  4  7  9  7  3  0  0  2  0  5 10  1 11 10  6
  8]
<built-in method min of numpy.ndarray object at 0x000001ECA5920150>
0
4
[[ 1.6844647   1.33291067 -1.04481749  1.04704049  0.30514304]
 [-0.29654259  0.09734604  1.64104765  1.49714061  0.195724  ]
 [ 1.61007729  0.26479022 -0.74882842  0.17239191  0.24335098]
 [-1.33765294 -1.60928367 -0.24049397 -0.02009511  0.48028918]
 [-0.20291191 -1.25836714  0.16293232 -0.29986362 -0.45522038]]
-1.6092836674552669
16


---
## Shape attribute (not method)
---

In [ ]:
# Shape -> the shape attibute gives us the shape of an 1D or 2D array.  As its a attribute we do not need parenthesis to call it

# For 1D vectors:
Vector = np.arange(0,18)           # gives a 1D array of 18 elements excluding 18
print(Vector)
print(Vector.shape)                # return-> (18,) indicating a 1D array with 18 elememts

Matrix = Vector.reshape(9,2)
print(Matrix)
print(Matrix.shape)               # returns-> (9,2) indicating a maxtrix of order 9x2

Matrix = Matrix.reshape(6,3)      # arrays in numpy are mutable so we can assing the same variable changed values(# Bit of info)
print(Matrix)
print(Matrix.shape)               # returns-> (6,3)

Matrix = Matrix.reshape(18,1)
print(Matrix)
print(Matrix.shape)              # returns (18,1) in this case as its a matrix and not a vector (previously-> (18,) for vectors)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
(18,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]]
(9, 2)
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
(6, 3)
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]]
(18, 1)


---
## dtype(attribute) : Data type an array is containing
---

In [ ]:
# It is same for both 1D and 2D array as it only returns the datatype of the elements in an array and space it is taking in bits

ve1 = np.random.randint(10,18,12)           # contains only intiges
print(ve1)
print(ve1.dtype)                            # output: int32--> indicating it contains 32 bit of intigers

ve2 = np.random.randint(10,18,55)           
print(ve2)
print(ve2.dtype)

ve3 = np.random.randn(18)
print(ve3)
print(ve3.dtype)                           # Output : float64 as it containts floating values


mat1 = np.random.randn(4,5)               # a matrix of order 4x5
print(mat1)
print(mat1.dtype)                         # ouput: float64

[17 13 17 12 10 12 10 12 13 11 12 16]
int32
[12 12 15 13 14 11 17 11 12 14 12 17 13 17 14 12 10 12 14 11 11 12 17 17
 17 16 14 12 15 10 10 11 14 16 14 17 17 10 10 15 11 12 16 17 14 12 16 11
 10 11 13 11 14 11 12]
int32
[ 0.81693975 -0.40888774 -2.17809791 -0.82083174  1.41061444 -0.25965194
  0.99148821 -1.0144992   0.67863869  0.53109582 -1.1363258   1.18411021
 -0.21950628 -0.38071824  0.02723027  0.50318567 -0.41729062 -1.03754838]
float64
[[ 1.50547325  1.05208469  0.31296038 -0.88655773 -0.44730764]
 [ 0.42201654  1.26369114  0.27418965  0.32097874 -0.36799862]
 [-0.66699538 -1.47742234  0.12460549 -0.54016346  0.92642107]
 [-1.07225756  1.69112466 -0.67158898  0.39972669 -1.52824601]]
float64


### 🧠 Understanding NumPy Integer Datatypes and Memory Capacity

In this context, the number of **bits** determines the minimum and maximum whole numbers that can be stored in each slot of a NumPy array. Choosing the right size helps optimize computer memory usage.

---

#### 📊 Bit Capacity Breakdown

| Datatype | Memory per Element | Minimum Value | Maximum Value | Best Used For |
| :--- | :--- | :--- | :--- | :--- |
| **`int8`** | 1 Byte (8 bits) | $-128$ | $127$ | Very small numbers (e.g., ages, days of the month) |
| **`int16`** | 2 Bytes (16 bits) | $-32,768$ | $32,767$ | Medium numbers (e.g., daily temperature records) |
| **`int32`** | 4 Bytes (32 bits) | $-2,147,483,648$ | $2,147,483,647$ | Standard calculations (e.g., city populations) |
| **`int64`** | 8 Bytes (64 bits) | $-9,223,372,036,854,775,808$ | $9,223,372,036,854,775,807$ | Massive values (e.g., financial ledger totals, scientific data) |

---

#### 🔍 What is Included in this Context?

1. **The Math Formula:** The total numbers a bit size can hold is calculated by $2^{\text{bits}}$. For signed integers (which support both negative and positive numbers), the formula for the maximum value is $2^{(\text{bits} - 1)} - 1$.
2. **Memory Efficiency:** Smaller bit sizes (like `int8`) use **8 times less memory** than larger sizes (like `int64`).
3. **The Overflow Risk:** If a calculation produces a number larger than the maximum capacity of its bit size, the data will **overflow**, resulting in broken or corrupted negative numbers.
---
### 🖥️ Default Bit Sizes: 32-bit vs. 64-bit Arrays

When you don't explicitly specify a `dtype`, NumPy automatically assigns a default bit size depending on your computer's operating system (OS) and the size of your numbers.

---

#### 📌 Which Array Becomes 32-bit?

An array will default to **`int32`** in the following scenarios:

1. **Windows OS Defaults:** On standard **Windows** machines, NumPy defaults to creating `int32` arrays for normal integer values.
2. **Explicit Declaration:** When you force the array to use 32-bit using `dtype=np.int32`.
3. **Decimals/Floating Points (`float32`):** If you create an array of decimal numbers and choose lower-precision floating points to save space.

---

#### 📌 Which Array Becomes 64-bit?

An array will default to **`int64`** in the following scenarios:

1. **Linux and macOS Defaults:** On modern 64-bit **Linux** and **Apple Mac** computers, NumPy automatically defaults to `int64` for all general integers.
2. **Massive Numbers:** If an integer on *any* operating system is too large to fit in a 32-bit limit (outside the range of $-2$ billion to $+2$ billion), NumPy automatically bumps it up to `int64`.
3. **Default Floating Points (`float64`):** When you create an array with decimals (e.g., `[1.5, 2.3, 4.0]`), NumPy defaults to 64-bit precision across all operating systems.


In [38]:
import numpy as np

# Create three arrays with the exact same 5 numbers, but different bit sizes
data = [10, 20, 30, 40, 50]

arr_int8 = np.array(data, dtype=np.int8)
arr_int32 = np.array(data, dtype=np.int32)
arr_int64 = np.array(data, dtype=np.int64)

# Print the total memory used by each array
print(f"📊 int8 array memory:  {arr_int8.nbytes} bytes")
print(f"📊 int32 array memory: {arr_int32.nbytes} bytes")
print(f"📊 int64 array memory: {arr_int64.nbytes} bytes")


📊 int8 array memory:  5 bytes
📊 int32 array memory: 20 bytes
📊 int64 array memory: 40 bytes


In [ ]:
# Example of storage space in bits

# 1. Small bucket (int8) - Uses very little memory
# Best for tiny numbers between -128 and 127
small_array = np.array([10, 15, 12], dtype=np.int8)
print("Small Array Type:", small_array.dtype)

# 2. Medium bucket (int32) - Your default size
# Best for normal numbers up to 2 billion
medium_array = np.array([10, 15, 12], dtype=np.int32)
print("Medium Array Type:", medium_array.dtype)

# 3. Large bucket (int64) - Uses the most memory
# Best for giant numbers up to 9 quintillion
large_array = np.array([10, 15, 12], dtype=np.int64)
print("Large Array Type:", large_array.dtype)


Small Array Type: int8
Medium Array Type: int32
Large Array Type: int64
