In [3]:
import numpy as np

In [4]:
# Creating reference array:
arr = np.arange(11)
print(arr)
arr1 = np.arange(7)
print(arr1)
arr2 = np.arange(7,14)
print(arr2)


[ 0  1  2  3  4  5  6  7  8  9 10]
[0 1 2 3 4 5 6]
[ 7  8  9 10 11 12 13]


---
### Numpy Arithmetic Operation
---

In [9]:
# Note: We can't do arithimatic operations(+,-,*,/) in arrays(1D or 2D) with different shapes and sizes. Hence:

print(arr+arr1)         # Value error: operands could not be broadcast together with shapes (11,) (7,)
print(arr+arr2)         # Value error : shape of arr -> (11,) and shape of arr2 -> (7,)

# While operating on an 1D array the output will also be in an 1D aray


ValueError: operands could not be broadcast together with shapes (11,) (7,) 

In [ ]:
# Sum: Elements of the first array gets added with the elements of the second array having the same index. Like idx0 element of 1st gets added with idx0 element of the second array

print(arr + arr)         # Output :[ 0  2  4  6  8 10 12 14 16 18 20]  as -> [0+0 1+1 2+2 3+3 4+4 .... 10+10]         
print(arr1 + arr2)       # Output : [ 7  9 11 13 15 17 19] as -> [0+7 1+8 2+9 3+10 4+11 5+12 6+13]


[ 0  2  4  6  8 10 12 14 16 18 20]
[ 7  9 11 13 15 17 19]


In [ ]:
# Difference : Elements of the first array gets subtracted from the elements of the second array having the same index. Like idx0 element of 1st gets added with idx0 element of the second array

print(arr-arr)           # Output : [0 0 0 0 0 0 0 0 0 0 0] as -> [0-0 1-1 2-2 3-3 4-4 5-5 6-6]
print(arr1-arr2)         # Output : [-7 -7 -7 -7 -7 -7 -7]  as -> [0-7 1-8 2-9 3-10 11-4 5-12 6-13]


[0 0 0 0 0 0 0 0 0 0 0]
[-7 -7 -7 -7 -7 -7 -7]


In [ ]:
# Product : Elements of the first array gets multiplied with the elements of the second array having the same index. Like idx0 element of 1st gets added with idx0 element of the second array

print(arr * arr)
print(arr1 * arr2)


[  0   1   4   9  16  25  36  49  64  81 100]
[ 0  8 18 30 44 60 78]


In [8]:
# Division : Elements of the first array gets from the elements of the second array having the same index. Like idx0 element of 1st gets added with idx0 element of the second array

# True division

print(arr/arr)                   # Gives runtimeWarning warning(not error) -> Output :[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.] 
# idx 0 of arr gets divided from idx0 of arr : As 0/0 is not definable its gives varning and corresponds that value to "nan"

print(arr1/arr2)     # No warning this time as here we haven't done 
# Output: [0.         0.125      0.22222222 0.3        0.36363636         0.41666667           0.46153846]

# Intiger Division:(floor division)

print(arr//arr)                  # Gives runtime warning(again) -> Output: [0 1 1 1 1 1 1 1 1 1 1] (different from arr/arr as there we were doing true division )
print(arr1//arr2)                # Ouput : [0 0 0 0 0 0 0] as neither of arr1 and arr2 gives intigers when divided 


[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[0.         0.125      0.22222222 0.3        0.36363636 0.41666667
 0.46153846]
[0 1 1 1 1 1 1 1 1 1 1]
[0 0 0 0 0 0 0]


C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\920168890.py:5: RuntimeWarning: invalid value encountered in divide
  print(arr/arr)                   # Gives runtimeWarning warning(not error) -> Output :[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\920168890.py:13: RuntimeWarning: divide by zero encountered in floor_divide
  print(arr//arr)                  # Gives runtime warning(again) -> Output: [0 1 1 1 1 1 1 1 1 1 1] (different from arr/arr as there we were doing true division )


In [17]:
# Edge cases of divisions:

ref1 = np.arange(0,11)
ref2 = np.arange(1,12)
print(ref1 , ref2, sep="\n")

# Case-I : 0/0 in array divison = "nan" with Runtime warning ; 0//0 in array division is = 0 with runtime warning
print(ref1/ref1)
print(ref1//ref1)

# Case-II : 1/0 in array division = "inf"(infinity) with runtime warning ; 1//0 in array division = 0 with runtime warning
print(ref2/ref1)
print(ref2//ref1)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10 11]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[0 1 1 1 1 1 1 1 1 1 1]
[       inf 2.         1.5        1.33333333 1.25       1.2
 1.16666667 1.14285714 1.125      1.11111111 1.1       ]
[0 2 1 1 1 1 1 1 1 1 1]


C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\1168848903.py:8: RuntimeWarning: invalid value encountered in divide
  print(ref1/ref1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\1168848903.py:9: RuntimeWarning: divide by zero encountered in floor_divide
  print(ref1//ref1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\1168848903.py:12: RuntimeWarning: divide by zero encountered in divide
  print(ref2/ref1)
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\1168848903.py:13: RuntimeWarning: divide by zero encountered in floor_divide
  print(ref2//ref1)


In [25]:
# Congruent: Same logic as of +,-,/,*
print(arr)
print(arr%arr)                # Output: [0 0 0 0 0 0 0 0 0 0 0](all these are remainders) . with runtime warning as division with 0 was encountered on idx 1
# Logic-> [0%0 1%1 2%2 3%3 4%4 5%5 6%6 7%7 8%8 9%9 10%10]
print(arr1%arr2)
print(ref1%ref2)
print(ref2%ref1)              # Runtime warning


[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 0 0 0 0 0 0 0 0 0]
[0 1 2 3 4 5 6]
[ 0  1  2  3  4  5  6  7  8  9 10]
[0 0 1 1 1 1 1 1 1 1 1]


C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\435448107.py:3: RuntimeWarning: divide by zero encountered in remainder
  print(arr%arr)                # Output: [0 0 0 0 0 0 0 0 0 0 0](all these are remainders) . with runtime warning as division with 0 was encountered on idx 1
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\435448107.py:8: RuntimeWarning: divide by zero encountered in remainder
  print(ref2%ref1)              # Runtime warning


In [27]:
# Exponent: Same logic as +,-,/,*
print(arr)
print(arr**arr)          # Logic -> [0**0 1**1 2**2 3**3 4**4 5**5 6**6 7**7 8**8 9**9 10**10]
print(arr1**arr2)
print(ref1**ref2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[          1           1           4          27         256        3125
       46656      823543    16777216   387420489 10000000000]
[          0           1         512       59049     4194304   244140625
 13060694016]
[           0            1            8           81         1024
        15625       279936      5764801    134217728   3486784401
 100000000000]


---
### Arithmatic Operation with scaler
---

In [40]:
# Arithmatic operations with array and a scaler:
print(arr)

# (+) : A certain scaler number will get added to each element at each index
print("(arr + 5) = (5 + arr) ==> ", arr +5)

# (-) : A certain scaler number will get subtracted from each element or each element will get subtracted from a certain number
print("(arr - 2) ==> ", arr-2)        # 2 is getting subracted from each element
print("(2 - arr) ==> ", 2-arr)        # each element is getting subtracted from 2

# (*) : A certain scaler number will get multiplied to each element at each index
print("(arr*3) = (3*arr) ==> ", arr*3)

# (/) and (//) : A certain scaler number will get divided from each element or each element will get divided from a certain number
print("(arr / 7) ==> ",arr/7)
print("(arr // 7) ==> ",arr//7)
print("(7/arr) ==> ",7/arr)           # Runtime warning
print("(7//arr) ==> ",7//arr)         # Runtime warning


# (**): each element of the array will be raised to the power of a scaler or the scaler will be raise to the power of each element
print("(3**arr) ==> ", 3**arr)    # Here 3 ** each element
print("(arr**3) ==> ", arr**3)    # Here each element ** 3

# (%) : Same logis as previous
print("(arr%8) ==> ",arr%8)       # Here each element % 8
print("(8%arr) ==> ",8%arr)       # Here 8 % each element alon with runtime warning


[ 0  1  2  3  4  5  6  7  8  9 10]
(arr + 5) = (5 + arr) ==>  [ 5  6  7  8  9 10 11 12 13 14 15]
(arr - 2) ==>  [-2 -1  0  1  2  3  4  5  6  7  8]
(2 - arr) ==>  [ 2  1  0 -1 -2 -3 -4 -5 -6 -7 -8]
(arr*3) = (3*arr) ==>  [ 0  3  6  9 12 15 18 21 24 27 30]
(arr / 7) ==>  [0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143]
(arr // 7) ==>  [0 0 0 0 0 0 0 1 1 1 1]
(7/arr) ==>  [       inf 7.         3.5        2.33333333 1.75       1.4
 1.16666667 1.         0.875      0.77777778 0.7       ]
(7//arr) ==>  [0 7 3 2 1 1 1 1 0 0 0]
(3**arr) ==>  [    1     3     9    27    81   243   729  2187  6561 19683 59049]
(arr**3) ==>  [   0    1    8   27   64  125  216  343  512  729 1000]
(arr%8) ==>  [0 1 2 3 4 5 6 7 0 1 2]
(8%arr) ==>  [0 0 0 2 0 3 2 1 0 8 8]


C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\712892070.py:17: RuntimeWarning: divide by zero encountered in divide
  print("(7/arr) ==> ",7/arr)           # Runtime warning
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\712892070.py:18: RuntimeWarning: divide by zero encountered in floor_divide
  print("(7//arr) ==> ",7//arr)         # Runtime warning
C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\712892070.py:27: RuntimeWarning: divide by zero encountered in remainder
  print("(8%arr) ==> ",8%arr)


---
# 🚀 NumPy Universal Functions (ufuncs), Aggregations & Broadcasting

A **universal function** (or **ufunc**) is a function that operates on `ndarrays` in an element-by-element fashion. They support **vectorization**, **broadcasting**, and **type casting**, making loops unnecessary in Python.

---

## 📋 Comprehensive Function List & Examples

### 1. Math & Arithmetic

| Function | Operator Equivalent | Description |
| :--- | :--- | :--- |
| `np.add(x1, x2)` | `x1 + x2` | Adds corresponding elements together. |
| `np.subtract(x1, x2)` | `x1 - x2` | Subtracts the second array from the first. |
| `np.multiply(x1, x2)` | `x1 * x2` | Multiplies elements together. |
| `np.divide(x1, x2)` | `x1 / x2` | Divides the first array by the second (returns floats). |
| `np.power(x1, x2)` | `x1 ** x2` | Raises elements of `x1` to the power of `x2`. |
| `np.negative(x)` | `-x` | Flips the sign of every element. |
| `np.sqrt(x)` | None | Calculates the square root of each element. |
| `np.absolute(x)` | `np.abs(x)` | Computes the absolute value. |

```python
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Example: Adding arrays
print(np.add(a, b))        # Output: [5 7 9]

# Example: Square root of a negative array after using absolute
neg_arr = np.array([-4, -9, -16])
print(np.sqrt(np.abs(neg_arr)))  # Output: [2. 3. 4.]
```

### 2. Trigonometry (Angles must be in Radians)

| Function | Description |
| :--- | :--- |
| `np.sin(x)` / `np.cos(x)` / `np.tan(x)` | Compute sine, cosine, and tangent. |
| `np.arcsin(x)` / `np.arccos(x)` / `np.arctan(x)` | Compute inverse trigonometric functions. |
| `np.deg2rad(x)` | Converts angles from degrees to radians. |
| `np.rad2deg(x)` | Converts angles from radians to degrees. |

```python
degrees = np.array([0, 30, 45, 60, 90])

# Example: Convert to radians and find sine values
radians = np.deg2rad(degrees)
print(np.sin(radians))  # Output: [0.  0.5  0.70710678  0.8660254  1.]
```

### 3. Exponents & Logarithms

| Function | Description |
| :--- | :--- |
| `np.exp(x)` | Computes \(e^x\) for each element. |
| `np.log(x)` | Computes the natural logarithm (base \(e\)). |
| `np.log2(x)` | Computes the base-2 logarithm. |
| `np.log10(x)` | Computes the base-10 logarithm. |

```python
x = np.array([1, 10, 100])

# Example: Base-10 log
print(np.log10(x))  # Output: [0. 1. 2.]
```

### 4. Comparison, Logic & Selection

| Function | Operator Equivalent | Description |
| :--- | :--- | :--- |
| `np.greater(x1, x2)` | `x1 > x2` | Element-wise truth value of `x1 > x2`. |
| `np.less(x1, x2)` | `x1 < x2` | Element-wise truth value of `x1 < x2`. |
| `np.equal(x1, x2)` | `x1 == x2` | Element-wise truth value of `x1 == x2`. |
| `np.logical_and(x1, x2)`| `&` (for bool arrays) | Element-wise truth value of `x1 AND x2`. |
| `np.logical_or(x1, x2)` | `\|` (for bool arrays) | Element-wise truth value of `x1 OR x2`. |
| `np.maximum(x1, x2)` | None | Returns element-wise maximums. |
| `np.minimum(x1, x2)` | None | Returns element-wise minimums. |

```python
arr1 = np.array([10, 5, 30])
arr2 = np.array([2, 12, 15])

# Example: Element-wise comparison selection
print(np.maximum(arr1, arr2))  # Output: [10 12 30]

# Example: Logical filtering
mask = np.logical_and(arr1 > 4, arr1 < 20)
print(arr1[mask])              # Output: [10]
```

### 5. Floating-Point & Rounding

| Function | Description |
| :--- | :--- |
| `np.floor(x)` | Rounds down to the nearest integer. |
| `np.ceil(x)` | Rounds up to the nearest integer. |
| `np.trunc(x)` | Chops off decimals, keeping only the integer part. |
| `np.isnan(x)` | Returns `True` if the element is Not a Number (`NaN`). |

```python
decimals = np.array([1.7, -2.3, np.nan])

print(np.floor(decimals))  # Output: [ 1. -3. nan]
print(np.isnan(decimals))   # Output: [False False  True]
```
---
### 📊 NumPy Statistical Functions Reference

| Function | Shortcut Variant | What it Calculates | Example Code |
| :--- | :--- | :--- | :--- |
| **`np.std(x)`** | `x.std()` | **Standard Deviation** (how spread out numbers are) | `np.std(matrix)` |
| **`np.var(x)`** | `x.var()` | **Variance** (average of squared differences from mean) | `np.var(matrix)` |
| **`np.mean(x)`** | `x.mean()` | **Mean** (the mathematical average) | `np.mean(matrix)` |
| **`np.median(x)`** | *None* | **Median** (the middle number in a sorted list) | `np.median(matrix)` |
| **`np.min(x)`** | `x.min()` | **Minimum** (the smallest number) | `np.min(matrix)` |
| **`np.max(x)`** | `x.max()` | **Maximum** (the largest number) | `np.max(matrix)` |
| **`np.sum(x)`** | `x.sum()` | **Sum** (adds all numbers together) | `np.sum(matrix)` |

> 💡 **Quick Tip:** Add `axis=0` to calculate by column, or `axis=1` to calculate by row for any function above!

---

## 📊 The Mean Function (`np.mean`)

While mathematical ufuncs keep the shape of your array unchanged, `np.mean` is an **aggregation function** (specifically a `numpy.ndarray` method wrapper). It condenses data down by finding the arithmetic average.

You can use it globally, or crunch numbers across specific structural grid directions using the `axis` parameter.

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# 1. Overall Mean (Flattens the entire grid)
print(np.mean(matrix))          # Output: 3.5

# 2. Column-wise Mean (Collapses rows down; Axis 0)
# (1+4)/2 , (2+5)/2 , (3+6)/2
print(np.mean(matrix, axis=0))  # Output: [2.5, 3.5, 4.5]

# 3. Row-wise Mean (Collapses columns across; Axis 1)
# (1+2+3)/3 , (4+5+6)/3
print(np.mean(matrix, axis=1))  # Output: [2., 5.]
```

💡 **Trick:** If your data contains missing `NaN` values, standard `np.mean` will break and return `nan`. Use **`np.nanmean()`** instead to completely skip missing values!
---
# 🧭 Understanding the NumPy `axis` Parameter

The **axis** parameter tells NumPy **which direction to look or collapse** when running an operation (like `np.mean()`, `np.sum()`, or `np.max()`) on a grid of numbers. 

Think of an axis as an **imaginary directional line** passing through your data block.

---

## 🗂️ The Golden Mental Models for 2D Arrays

In a 2D grid (a matrix), shapes are written as `(Rows, Columns)`. NumPy indexes axes in that exact same order:
*   **`axis=0`**: The **Row** axis. It points **down** ⬇️
*   **`axis=1`**: The **Column** axis. It points **across** ➡️

---

## 🎨 Visual Diagram of Array Crushing

Instead of thinking about "looping," imagine that passing an axis to an aggregation function physically **crushes** or **compresses** the data along that specific path.

### 1. `axis = 0` (Vertical Action / Crush the Rows)
NumPy travels **vertically down** the table. It smashes all the rows down into a single horizontal strip. 
*   **Result:** You get a separate calculation for **each column**.

```text
       Column 1   Column 2   Column 3
Row 1: [  1          2          3  ]
          │          │          │
          ▼          ▼          ▼     (Smashes Downwards ⬇️)
Row 2: [  4          5          6  ]
====================================
Mean:  [ 2.5        3.5        4.5 ]  <- Leaves 1 Row vector
```

### 2. `axis = 1` (Horizontal Action / Crush the Columns)
NumPy travels **horizontally across** the table. It smashes all the columns sideways into a single vertical strip.
*   **Result:** You get a separate calculation for **each row**.

```text
       Column 1   Column 2   Column 3        Mean Result
Row 1: [  1   ───────────────>   3  ]  ====>   [ 2.0 ]
Row 2: [  4   ───────────────>   6  ]  ====>   [ 5.0 ]
                                                  ▲
                                         Leaves 1 Column vector
```

---

## 🎯 The "Shape Eraser" Math Trick

If you ever get confused about what your data will look like after using an axis, use the **Shape Eraser Trick**:

1. Write down the shape of your starting array. (Example: `(5, 8)`)
2. Look at the number you chose for the `axis` parameter.
3. **Completely erase** that index position from your original shape statement!

*   **`axis=0`**: Erase index 0. Shape `(5, 8)` becomes `(8,)`.
*   **`axis=1`**: Erase index 1. Shape `(5, 8)` becomes `(5,)`.

---

## 💻 Quick Code Implementation

```python
import numpy as np

# Create a 2D matrix of 2 rows and 3 columns
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

# Crunch down rows (find mean of each column)
print("Axis 0 Mean:", np.mean(matrix, axis=0)) 
# Output: [2.5, 3.5, 4.5]

# Crunch across columns (find mean of each row)
print("Axis 1 Mean:", np.mean(matrix, axis=1)) 
# Output: [2.0, 5.0]
```

---

## 🛜 The Magic of Broadcasting Rules

What happens if you use a ufunc on arrays with **different shapes**? NumPy uses **broadcasting** to virtually stretch the smaller array to match the larger one without wasting real computer memory.

### The 2 Golden Rules of Broadcasting
Two dimensions are compatible if:
1. They are **exactly equal** in size.
2. One of them is **exactly 1**.

NumPy checks shapes from **right to left** (starting at the last dimension).

### Visualization Examples

#### Case A: Stretching a Single Scalar
```text
Array A (2x3): [[1, 2, 3],         Scalar B: [10] (stretches to match A)]          
                
    [[1, 2, 3],      +   [[10, 10, 10],      =   [[11, 12, 13],
]  ]  ]
```

#### Case B: Stretching a 1D Row Vector across a 2D Matrix
```text
Array A (2x3): [[1, 2, 3],         Vector B (1x3): [10, 20, 30] (stretches down)]          
                
    [[1, 2, 3],      +   [[10, 20, 30],      =   [[11, 22, 33],
]  ]  ]
```

### Broadcasting Code Sample
```python
# A matrix of shape (3, 3)
matrix_3x3 = np.zeros((3, 3)) 

# A row vector of shape (3,)
row_vector = np.array([1, 2, 3])

# Even though shapes don't match, rule #2 lets row_vector stretch downward!
result = np.add(matrix_3x3, row_vector)
print(result)
# Output:
# [[1. 2. 3.]
#  [1. 2. 3.]
#  [1. 2. 3.]]
```

---

## 💡 Hidden Tricks & Special Methods

Every NumPy ufunc has built-in helper methods that make them even more powerful.

### Trick 1: Save Memory with `out=`
Normally, operations like `y = np.sin(x)` create a brand-new array in memory. If your data is huge, you can write the results directly into an existing array to save space.
```python
large_arr = np.arange(1000000, dtype=np.float64)
output_arr = np.empty_like(large_arr)

# Instead of creating new memory, reuse output_arr
np.sin(large_arr, out=output_arr)
```

### Trick 2: Matrix Grid math with `.outer`
You can apply a ufunc to all possible pairs between two different arrays to generate custom multiplication tables or grids instantly.
```python
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

# Multiplies every element of 'a' with every element of 'b'
print(np.multiply.outer(a, b))
# Output:
# [[10 20 30]
#  [20 40 60]
#  [30 60 90]]
```

### Trick 3: Cumulative Math with `.accumulate`
Track the step-by-step history of a ufunc calculation across an entire array.
```python
nums = np.array([1, 2, 3, 4])

# Shows the running total of adding numbers together
print(np.add.accumulate(nums))  # Output: [1 3 6 10]
```

### Trick 4: Conditional Math with `where=`
You can tell a ufunc to only calculate numbers that match a specific condition, leaving the rest untouched.
```python
data = np.array([1.0, 4.0, -9.0, 16.0])
result = np.zeros_like(data)

# Only calculate square roots for numbers greater than zero
np.sqrt(data, where=(data > 0), out=result)
print(result)  # Output: [1. 2. 0. 4.]
```
---
---
https://numpy.org/doc/stable/reference/routines.statistics.html
---
---

In [43]:
# Reference array:
array = np.arange(0,13)
print(array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
# Square root:
print(np.sqrt(array))         # takes square root of eact element in the array

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766 3.31662479
 3.46410162]


In [45]:
# Doing square:
print(np.square(array))        # takes square of every element

[  0   1   4   9  16  25  36  49  64  81 100 121 144]


In [49]:
# Max value and min value :
print(np.max(array))             # gives the maximum value of an array
# Same as
print(array.max())


print(np.min(array))          # Gives minimum value in the array
# Same as 
print(array.min())

12
12
0
0


In [51]:
# Exponent (e^ (array element))
print(np.exp(array))               # e ** each element

[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04
 1.62754791e+05]


In [52]:
# Log
print(np.log(array))                # runtime warning as log 0 = -infinity(divide by zero)

[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458 2.30258509 2.39789527
 2.48490665]


C:\Users\Admin\AppData\Local\Temp\ipykernel_10372\4147912084.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(array))


In [53]:
# Trigo Functions
print(np.sin(array))            # assumes each element to be in radian and does sin operation
print(np.cos(array))            # assumes each element to be in radian and does cos operation

[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849 -0.54402111 -0.99999021
 -0.53657292]
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026 -0.83907153  0.0044257
  0.84385396]


In [ ]:
# Statistical Function

print(np.std(array))                        # Standard deviation without axis specification
print(np.std(array, axis=0))                # takes standard devition downwards along column
# print(np.std(array,axis=1))               # Error as 1D matrix has only axis 0

matrix = np.arange(0,13).reshape(1,13)
print(matrix)                               # same elements 2D array

print(np.std(matrix,axis=1))                # take standard deviation from left to righ rowwise for a 2D array

# Similar for variance


3.7416573867739413
3.7416573867739413
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12]]
[3.74165739]


In [62]:
# Sum of all elements in an array:

print(np.sum(array))                    # adds all the elemnts of an array (different from sim)
print(np.sum(matrix))                   # we can also specify axis here to get row-wise or column-wise sums


78
78


In [ ]:
# The full function: Creates an array have all elements similar (quite same as ones and zeros but here every element can be repeated)

print(np.full(8,12))       # prints an array with 8 , 12's

print(np.full(14,3).reshape(7,2))          # Can also create a 2D matrix
# Or 
print(np.full((7,2),3))                    # Does the same thing
# Also
print(np.full((5,5),[1,2,3,4,5]))          # creates a matrix with every row as 1,2,3,4,5



[12 12 12 12 12 12 12 12]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
